Failure # 1 (occurred at 2024-03-26_14-29-16)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=14208, ip=127.0.0.1, actor_id=f3d53c0d2cf68b5a6dd5d2e901000000, repr=PPO)
  File "python\ray\_raylet.pyx", line 1889, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1830, in ray._raylet.execute_task.function_executor
  File "c:\Users\josep\Documents\Coup-RL\env\lib\site-packages\ray\_private\function_manager.py", line 724, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "c:\Users\josep\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "c:\Users\josep\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 456, in __init__
    self._env_id, self.env_creator = self._get_env_id_and_creator(
  File "c:\Users\josep\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2628, in _get_env_id_and_creator
    return env_specifier, _global_registry.get(ENV_CREATOR, env_specifier)
  File "c:\Users\josep\Documents\Coup-RL\env\lib\site-packages\ray\tune\registry.py", line 270, in get
    return pickle.loads(value)
  File "c:\Users\josep\Documents\Coup-RL\env\lib\site-packages\ray\cloudpickle\cloudpickle.py", line 457, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'coup_v1'
