Failure # 1 (occurred at 2024-04-21_20-02-58)
[36mray::PPO.train()[39m (pid=10264, ip=127.0.0.1, actor_id=a6a453f3f2b50cf350cbaa0101000000, repr=PPO)
  File "python\ray\_raylet.pyx", line 1889, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1830, in ray._raylet.execute_task.function_executor
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\_private\function_manager.py", line 724, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\tune\trainable\trainable.py", line 334, in train
    raise skipped from exception_cause(skipped)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\tune\trainable\trainable.py", line 331, in train
    result = self.step()
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 849, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 3194, in _run_one_training_iteration
    results = self.training_step()
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 410, in training_step
    return self._training_step_old_and_hybrid_api_stacks()
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 495, in _training_step_old_and_hybrid_api_stacks
    train_batch = synchronous_parallel_sample(
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 88, in synchronous_parallel_sample
    sampled_data = worker_set.foreach_worker(
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 771, in foreach_worker
    handle_remote_call_result_errors(remote_results, self._ignore_worker_failures)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\worker_set.py", line 78, in handle_remote_call_result_errors
    raise r.get()
ray.exceptions.RayTaskError(RuntimeError): [36mray::RolloutWorker.apply()[39m (pid=10264, ip=127.0.0.1, actor_id=3176032048001ca3faed057301000000, repr=<ray.rllib.evaluation.rollout_worker._modify_class.<locals>.Class object at 0x00000207F425F280>)
  File "python\ray\_raylet.pyx", line 1889, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1830, in ray._raylet.execute_task.function_executor
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\_private\function_manager.py", line 724, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\utils\actor_manager.py", line 189, in apply
    raise e
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\utils\actor_manager.py", line 178, in apply
    return func(self, *args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\execution\rollout_ops.py", line 89, in <lambda>
    lambda w: w.sample(), local_worker=False, healthy_only=True
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 694, in sample
    batches = [self.input_reader.next()]
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\sampler.py", line 91, in next
    batches = [self.get_data()]
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\sampler.py", line 273, in get_data
    item = next(self._env_runner)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 348, in run
    outputs = self.step()
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 386, in step
    eval_results = self._do_policy_eval(to_eval=to_eval)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\evaluation\env_runner_v2.py", line 1086, in _do_policy_eval
    eval_results[policy_id] = policy.compute_actions_from_input_dict(
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 557, in compute_actions_from_input_dict
    return self._compute_action_helper(
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\utils\threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\policy\torch_policy_v2.py", line 1260, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches, seq_lens)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\models\modelv2.py", line 255, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\examples\models\action_mask_model.py", line 111, in forward
    logits, _ = self.internal_model({"obs": input_dict["obs"]["observations"]})
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\models\modelv2.py", line 255, in __call__
    res = self.forward(restored, state or [], seq_lens)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\models\torch\fcnet.py", line 147, in forward
    self._features = self._hidden_layers(self._last_flat_in)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\models\torch\misc.py", line 297, in forward
    return self._model(x)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\torch\nn\modules\linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x20 and 12x256)
