Failure # 1 (occurred at 2024-04-21_20-02-19)
[36mray::PPO.train()[39m (pid=10264, ip=127.0.0.1, actor_id=ed274681660ec72503851d0701000000, repr=PPO)
  File "python\ray\_raylet.pyx", line 1889, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1830, in ray._raylet.execute_task.function_executor
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\_private\function_manager.py", line 724, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\tune\trainable\trainable.py", line 334, in train
    raise skipped from exception_cause(skipped)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\tune\trainable\trainable.py", line 331, in train
    result = self.step()
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 853, in step
    results.update(self._run_one_evaluation(train_future=None))
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 3239, in _run_one_evaluation
    eval_results = eval_func_to_use()
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\util\tracing\tracing_helper.py", line 467, in _resume_span
    return method(self, *_args, **_kwargs)
  File "D:\Documents\Coup-RL\env\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 948, in evaluate
    metrics = self.config.custom_evaluation_function(
  File "D:\Documents\Coup-RL\Coup\coup\train_ppo.py", line 287, in custom_eval_function
    eval_policy_tests(eval_workers, metrics)
  File "D:\Documents\Coup-RL\Coup\coup\train_ppo.py", line 254, in eval_policy_tests
    env = eval_workers.local_worker().env_creator({}).env
  File "D:\Documents\Coup-RL\Coup\coup\train_ppo.py", line 333, in <lambda>
    register_env("Coup", lambda config: PettingZooEnv(env_creator(config)))
  File "D:\Documents\Coup-RL\Coup\coup\train_ppo.py", line 304, in env_creator
    env = coup_v2.env(k_actions=config["k_actions"])
KeyError: 'k_actions'
